name: homepage

services:
  homepage-backend:
    build: ./backend
    container_name: homepage-backend
    ports:
      - "8000:8000"  # Keep external port for direct access if needed
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    networks:
      - homepage-network

  homepage-frontend:
    build: ./frontend
    container_name: homepage-frontend
    ports:
      - "3000:3000"
    depends_on:
      - homepage-backend
    restart: unless-stopped
    environment:
      - BACKEND_BASE_URL=http://localhost:8000
    networks:
      - homepage-network

networks:
  homepage-network:
    driver: bridge
